- name: first playbook
  hosts: all
  become: true
  tasks:
    - name: apt update
      apt:
        update_cache: true

    - apt:
        name:
          - vim
          - tmux
          - emacs
          - git
          - nginx
          - nodejs
          - mariadb-server
          - fail2ban
